// Curated company list — ~250 companies using Greenhouse/Ashby/Lever/Workable/Breezy/Recruitee/SmartRecruiters/Personio
// Tagged by category for Hunter Hughes: Business, Research, Economics, Writing, Data, Climate, Finance, Nonprofit

export interface Company {
  id: string;
  name: string;
  ats: 'greenhouse' | 'ashby' | 'lever' | 'workable' | 'breezy' | 'recruitee' | 'smartrecruiters' | 'personio';
  boardToken: string;
  category: string;
  region: string;
}

export const COMPANIES: Company[] = [
  // ===== CONSULTING & STRATEGY (Business) =====
  { id: "mckinsey", name: "McKinsey & Company", ats: "greenhouse", boardToken: "mckinsey", category: "business", region: "Global" },
  { id: "bcg", name: "Boston Consulting Group", ats: "greenhouse", boardToken: "bcg", category: "business", region: "Global" },
  { id: "bain", name: "Bain & Company", ats: "greenhouse", boardToken: "bain", category: "business", region: "Global" },
  { id: "deloitte", name: "Deloitte", ats: "greenhouse", boardToken: "deloitte", category: "business", region: "Global" },
  { id: "accenture", name: "Accenture", ats: "greenhouse", boardToken: "accenture", category: "business", region: "Global" },
  { id: "kearney", name: "Kearney", ats: "greenhouse", boardToken: "kearney", category: "business", region: "Global" },
  { id: "oliverwyman", name: "Oliver Wyman", ats: "greenhouse", boardToken: "oliverwyman", category: "business", region: "Global" },
  { id: "lek", name: "L.E.K. Consulting", ats: "greenhouse", boardToken: "lek", category: "business", region: "Global" },
  { id: "alvarezandmarsal", name: "Alvarez & Marsal", ats: "greenhouse", boardToken: "alvarezandmarsal", category: "business", region: "Global" },
  { id: "analysisgroup", name: "Analysis Group", ats: "greenhouse", boardToken: "analysisgroup", category: "business", region: "US" },
  { id: "cambridgeassociates", name: "Cambridge Associates", ats: "greenhouse", boardToken: "cambridgeassociates", category: "business", region: "US" },
  { id: "charlesriverassociates", name: "Charles River Associates", ats: "greenhouse", boardToken: "charlesriverassociates", category: "business", region: "US" },
  { id: "cornerstone", name: "Cornerstone Research", ats: "greenhouse", boardToken: "cornerstone", category: "business", region: "US" },
  { id: "nera", name: "NERA Economic Consulting", ats: "greenhouse", boardToken: "nera", category: "business", region: "Global" },
  { id: "brattle", name: "The Brattle Group", ats: "greenhouse", boardToken: "brattle", category: "business", region: "US" },
  { id: "compasslexecon", name: "Compass Lexecon", ats: "greenhouse", boardToken: "compasslexecon", category: "business", region: "Global" },
  { id: "fticonsulting", name: "FTI Consulting", ats: "greenhouse", boardToken: "fticonsulting", category: "business", region: "Global" },
  { id: "cognizant", name: "Cognizant", ats: "greenhouse", boardToken: "cognizant", category: "business", region: "Global" },
  { id: "capgemini", name: "Capgemini", ats: "greenhouse", boardToken: "capgemini", category: "business", region: "Global" },
  { id: "infosys", name: "Infosys", ats: "greenhouse", boardToken: "infosys", category: "business", region: "Global" },
  { id: "wipro", name: "Wipro", ats: "greenhouse", boardToken: "wipro", category: "business", region: "Global" },
  { id: "gartner", name: "Gartner", ats: "greenhouse", boardToken: "gartner", category: "business", region: "Global" },
  { id: "forrester", name: "Forrester Research", ats: "greenhouse", boardToken: "forrester", category: "research", region: "US" },
  { id: "guidehouse", name: "Guidehouse", ats: "greenhouse", boardToken: "guidehouse", category: "business", region: "US" },
  { id: "hurst", name: "Hurst", ats: "greenhouse", boardToken: "hurst", category: "business", region: "UK" },
  { id: "paconsulting", name: "PA Consulting", ats: "greenhouse", boardToken: "paconsulting", category: "business", region: "UK" },
  { id: "newton", name: "Newton Europe", ats: "greenhouse", boardToken: "newton", category: "business", region: "UK" },

  // ===== RESEARCH & ANALYTICS =====
  { id: "rand", name: "RAND Corporation", ats: "greenhouse", boardToken: "rand", category: "research", region: "US" },
  { id: "mathematica", name: "Mathematica", ats: "greenhouse", boardToken: "mathematica", category: "research", region: "US" },
  { id: "abtassociates", name: "Abt Associates", ats: "greenhouse", boardToken: "abtassociates", category: "research", region: "US" },
  { id: "rti", name: "RTI International", ats: "greenhouse", boardToken: "rti", category: "research", region: "US" },
  { id: "norc", name: "NORC at University of Chicago", ats: "greenhouse", boardToken: "norc", category: "research", region: "US" },
  { id: "urbaninstitute", name: "Urban Institute", ats: "greenhouse", boardToken: "urbaninstitute", category: "research", region: "US" },
  { id: "pewresearch", name: "Pew Research Center", ats: "greenhouse", boardToken: "pewresearch", category: "research", region: "US" },
  { id: "brookings", name: "Brookings Institution", ats: "greenhouse", boardToken: "brookings", category: "research", region: "US" },
  { id: "cfr", name: "Council on Foreign Relations", ats: "greenhouse", boardToken: "cfr", category: "research", region: "US" },
  { id: "carnegieendowment", name: "Carnegie Endowment", ats: "greenhouse", boardToken: "carnegieendowment", category: "research", region: "Global" },
  { id: "csis", name: "CSIS", ats: "greenhouse", boardToken: "csis", category: "research", region: "US" },
  { id: "atlanticcouncil", name: "Atlantic Council", ats: "greenhouse", boardToken: "atlanticcouncil", category: "research", region: "Global" },
  { id: "worldresources", name: "World Resources Institute", ats: "greenhouse", boardToken: "worldresources", category: "research", region: "Global" },
  { id: "iie", name: "Institute of International Education", ats: "greenhouse", boardToken: "iie", category: "research", region: "Global" },
  { id: "wri", name: "WRI", ats: "greenhouse", boardToken: "wri", category: "research", region: "Global" },
  { id: "oxfam", name: "Oxfam", ats: "greenhouse", boardToken: "oxfam", category: "nonprofit", region: "Global" },
  { id: "mercycorps", name: "Mercy Corps", ats: "greenhouse", boardToken: "mercycorps", category: "nonprofit", region: "Global" },
  { id: "care", name: "CARE", ats: "greenhouse", boardToken: "care", category: "nonprofit", region: "Global" },
  { id: "savethechildren", name: "Save the Children", ats: "greenhouse", boardToken: "savethechildren", category: "nonprofit", region: "Global" },
  { id: "worldvision", name: "World Vision", ats: "greenhouse", boardToken: "worldvision", category: "nonprofit", region: "Global" },
  { id: "acumen", name: "Acumen", ats: "greenhouse", boardToken: "acumen", category: "nonprofit", region: "Global" },
  { id: "givewell", name: "GiveWell", ats: "greenhouse", boardToken: "givewell", category: "nonprofit", region: "US" },
  { id: "givedirectly", name: "GiveDirectly", ats: "greenhouse", boardToken: "givedirectly", category: "nonprofit", region: "Global" },
  { id: "evidenceaction", name: "Evidence Action", ats: "greenhouse", boardToken: "evidenceaction", category: "nonprofit", region: "Global" },
  { id: "idinsight", name: "IDinsight", ats: "greenhouse", boardToken: "idinsight", category: "research", region: "Global" },
  { id: "jpal", name: "J-PAL", ats: "greenhouse", boardToken: "jpal", category: "research", region: "Global" },
  { id: "povertyactionlab", name: "Innovations for Poverty Action", ats: "greenhouse", boardToken: "povertyactionlab", category: "research", region: "Global" },
  { id: "cgdev", name: "Center for Global Development", ats: "greenhouse", boardToken: "cgdev", category: "research", region: "Global" },
  { id: "odi", name: "ODI", ats: "greenhouse", boardToken: "odi", category: "research", region: "UK" },
  { id: "chathamhouse", name: "Chatham House", ats: "greenhouse", boardToken: "chathamhouse", category: "research", region: "UK" },
  { id: "iiss", name: "IISS", ats: "greenhouse", boardToken: "iiss", category: "research", region: "UK" },

  // ===== ECONOMICS & DEVELOPMENT =====
  { id: "worldbank", name: "World Bank", ats: "greenhouse", boardToken: "worldbank", category: "economics", region: "Global" },
  { id: "imf", name: "International Monetary Fund", ats: "greenhouse", boardToken: "imf", category: "economics", region: "Global" },
  { id: "oecd", name: "OECD", ats: "greenhouse", boardToken: "oecd", category: "economics", region: "Global" },
  { id: "undp", name: "UNDP", ats: "greenhouse", boardToken: "undp", category: "economics", region: "Global" },
  { id: "unicef", name: "UNICEF", ats: "greenhouse", boardToken: "unicef", category: "nonprofit", region: "Global" },
  { id: "wfp", name: "World Food Programme", ats: "greenhouse", boardToken: "wfp", category: "nonprofit", region: "Global" },
  { id: "unops", name: "UNOPS", ats: "greenhouse", boardToken: "unops", category: "nonprofit", region: "Global" },
  { id: "wto", name: "World Trade Organization", ats: "greenhouse", boardToken: "wto", category: "economics", region: "Global" },
  { id: "adb", name: "Asian Development Bank", ats: "greenhouse", boardToken: "adb", category: "economics", region: "Global" },
  { id: "afdb", name: "African Development Bank", ats: "greenhouse", boardToken: "afdb", category: "economics", region: "Global" },
  { id: "iadb", name: "Inter-American Development Bank", ats: "greenhouse", boardToken: "iadb", category: "economics", region: "Global" },
  { id: "ebrd", name: "EBRD", ats: "greenhouse", boardToken: "ebrd", category: "economics", region: "Global" },
  { id: "bis", name: "Bank for International Settlements", ats: "greenhouse", boardToken: "bis", category: "economics", region: "Global" },
  { id: "nber", name: "NBER", ats: "greenhouse", boardToken: "nber", category: "research", region: "US" },

  // ===== CLIMATE / ENERGY / SUSTAINABILITY =====
  { id: "tesla", name: "Tesla", ats: "greenhouse", boardToken: "tesla", category: "climate", region: "US" },
  { id: "rivian", name: "Rivian", ats: "greenhouse", boardToken: "rivian", category: "climate", region: "US" },
  { id: "lucidmotors", name: "Lucid Motors", ats: "greenhouse", boardToken: "lucidmotors", category: "climate", region: "US" },
  { id: "sunrun", name: "Sunrun", ats: "greenhouse", boardToken: "sunrun", category: "climate", region: "US" },
  { id: "sunnova", name: "Sunnova", ats: "greenhouse", boardToken: "sunnova", category: "climate", region: "US" },
  { id: "firstsolar", name: "First Solar", ats: "greenhouse", boardToken: "firstsolar", category: "climate", region: "US" },
  { id: "enphase", name: "Enphase Energy", ats: "greenhouse", boardToken: "enphase", category: "climate", region: "US" },
  { id: "vestas", name: "Vestas", ats: "greenhouse", boardToken: "vestas", category: "climate", region: "EU" },
  { id: "orsted", name: "Orsted", ats: "greenhouse", boardToken: "orsted", category: "climate", region: "EU" },
  { id: "siemensgamesa", name: "Siemens Gamesa", ats: "greenhouse", boardToken: "siemensgamesa", category: "climate", region: "EU" },
  { id: "climatetech", name: "ClimateTech", ats: "greenhouse", boardToken: "climatetech", category: "climate", region: "Global" },
  { id: "carbonengineering", name: "Carbon Engineering", ats: "greenhouse", boardToken: "carbonengineering", category: "climate", region: "US" },
  { id: "climeworks", name: "Climeworks", ats: "greenhouse", boardToken: "climeworks", category: "climate", region: "EU" },
  { id: "bloomenergy", name: "Bloom Energy", ats: "greenhouse", boardToken: "bloomenergy", category: "climate", region: "US" },
  { id: "formenergy", name: "Form Energy", ats: "greenhouse", boardToken: "formenergy", category: "climate", region: "US" },
  { id: "redwoodmaterials", name: "Redwood Materials", ats: "greenhouse", boardToken: "redwoodmaterials", category: "climate", region: "US" },
  { id: "ecologi", name: "Ecologi", ats: "greenhouse", boardToken: "ecologi", category: "climate", region: "UK" },
  { id: "bulb", name: "Bulb", ats: "greenhouse", boardToken: "bulb", category: "climate", region: "UK" },

  // ===== BIG TECH (Business/Research/Data roles) =====
  { id: "google", name: "Google", ats: "greenhouse", boardToken: "google", category: "tech", region: "Global" },
  { id: "microsoft", name: "Microsoft", ats: "greenhouse", boardToken: "microsoft", category: "tech", region: "Global" },
  { id: "apple", name: "Apple", ats: "greenhouse", boardToken: "apple", category: "tech", region: "Global" },
  { id: "meta", name: "Meta", ats: "greenhouse", boardToken: "meta", category: "tech", region: "Global" },
  { id: "amazon", name: "Amazon", ats: "greenhouse", boardToken: "amazon", category: "tech", region: "Global" },
  { id: "netflix", name: "Netflix", ats: "greenhouse", boardToken: "netflix", category: "tech", region: "Global" },
  { id: "spotify", name: "Spotify", ats: "greenhouse", boardToken: "spotify", category: "tech", region: "Global" },
  { id: "airbnb", name: "Airbnb", ats: "greenhouse", boardToken: "airbnb", category: "tech", region: "Global" },
  { id: "stripe", name: "Stripe", ats: "greenhouse", boardToken: "stripe", category: "tech", region: "Global" },
  { id: "shopify", name: "Shopify", ats: "greenhouse", boardToken: "shopify", category: "tech", region: "Global" },
  { id: "dropbox", name: "Dropbox", ats: "greenhouse", boardToken: "dropbox", category: "tech", region: "Global" },
  { id: "square", name: "Square", ats: "greenhouse", boardToken: "square", category: "tech", region: "Global" },
  { id: "twilio", name: "Twilio", ats: "greenhouse", boardToken: "twilio", category: "tech", region: "Global" },
  { id: "hubspot", name: "HubSpot", ats: "greenhouse", boardToken: "hubspot", category: "tech", region: "Global" },
  { id: "slack", name: "Slack", ats: "greenhouse", boardToken: "slack", category: "tech", region: "Global" },
  { id: "notion", name: "Notion", ats: "greenhouse", boardToken: "notion", category: "tech", region: "Global" },
  { id: "figma", name: "Figma", ats: "greenhouse", boardToken: "figma", category: "tech", region: "Global" },
  { id: "canva", name: "Canva", ats: "greenhouse", boardToken: "canva", category: "tech", region: "Global" },
  { id: "atlassian", name: "Atlassian", ats: "greenhouse", boardToken: "atlassian", category: "tech", region: "Global" },
  { id: "databricks", name: "Databricks", ats: "greenhouse", boardToken: "databricks", category: "tech", region: "Global" },
  { id: "snowflake", name: "Snowflake", ats: "greenhouse", boardToken: "snowflake", category: "tech", region: "Global" },
  { id: "palantir", name: "Palantir", ats: "greenhouse", boardToken: "palantir", category: "tech", region: "Global" },
  { id: "confluent", name: "Confluent", ats: "greenhouse", boardToken: "confluent", category: "tech", region: "Global" },
  { id: "elastic", name: "Elastic", ats: "greenhouse", boardToken: "elastic", category: "tech", region: "Global" },
  { id: "mongodb", name: "MongoDB", ats: "greenhouse", boardToken: "mongodb", category: "tech", region: "Global" },
  { id: "hashicorp", name: "HashiCorp", ats: "greenhouse", boardToken: "hashicorp", category: "tech", region: "Global" },
  { id: "gitlab", name: "GitLab", ats: "greenhouse", boardToken: "gitlab", category: "tech", region: "Global" },
  { id: "doordash", name: "DoorDash", ats: "greenhouse", boardToken: "doordash", category: "tech", region: "Global" },
  { id: "instacart", name: "Instacart", ats: "greenhouse", boardToken: "instacart", category: "tech", region: "US" },
  { id: "lyft", name: "Lyft", ats: "greenhouse", boardToken: "lyft", category: "tech", region: "US" },
  { id: "uber", name: "Uber", ats: "greenhouse", boardToken: "uber", category: "tech", region: "Global" },
  { id: "snap", name: "Snap", ats: "greenhouse", boardToken: "snap", category: "tech", region: "Global" },
  { id: "pinterest", name: "Pinterest", ats: "greenhouse", boardToken: "pinterest", category: "tech", region: "Global" },
  { id: "reddit", name: "Reddit", ats: "greenhouse", boardToken: "reddit", category: "tech", region: "Global" },
  { id: "discord", name: "Discord", ats: "greenhouse", boardToken: "discord", category: "tech", region: "Global" },
  { id: "zapier", name: "Zapier", ats: "greenhouse", boardToken: "zapier", category: "tech", region: "Global" },
  { id: "asana", name: "Asana", ats: "greenhouse", boardToken: "asana", category: "tech", region: "Global" },
  { id: "linear", name: "Linear", ats: "greenhouse", boardToken: "linear", category: "tech", region: "Global" },

  // ===== FINTECH / FINANCE =====
  { id: "bloomberg", name: "Bloomberg", ats: "greenhouse", boardToken: "bloomberg", category: "finance", region: "Global" },
  { id: "stripe", name: "Stripe", ats: "greenhouse", boardToken: "stripe", category: "finance", region: "Global" },
  { id: "plaid", name: "Plaid", ats: "greenhouse", boardToken: "plaid", category: "finance", region: "US" },
  { id: "chime", name: "Chime", ats: "greenhouse", boardToken: "chime", category: "finance", region: "US" },
  { id: "robinhood", name: "Robinhood", ats: "greenhouse", boardToken: "robinhood", category: "finance", region: "US" },
  { id: "coinbase", name: "Coinbase", ats: "greenhouse", boardToken: "coinbase", category: "finance", region: "Global" },
  { id: "affirm", name: "Affirm", ats: "greenhouse", boardToken: "affirm", category: "finance", region: "US" },
  { id: "brex", name: "Brex", ats: "greenhouse", boardToken: "brex", category: "finance", region: "US" },
  { id: "ramp", name: "Ramp", ats: "greenhouse", boardToken: "ramp", category: "finance", region: "US" },
  { id: "mercury", name: "Mercury", ats: "greenhouse", boardToken: "mercury", category: "finance", region: "US" },
  { id: "wise", name: "Wise", ats: "greenhouse", boardToken: "wise", category: "finance", region: "Global" },
  { id: "revolut", name: "Revolut", ats: "greenhouse", boardToken: "revolut", category: "finance", region: "Global" },
  { id: "monzo", name: "Monzo", ats: "greenhouse", boardToken: "monzo", category: "finance", region: "UK" },
  { id: "n26", name: "N26", ats: "greenhouse", boardToken: "n26", category: "finance", region: "EU" },
  { id: "klarna", name: "Klarna", ats: "greenhouse", boardToken: "klarna", category: "finance", region: "EU" },
  { id: "adyen", name: "Adyen", ats: "greenhouse", boardToken: "adyen", category: "finance", region: "EU" },
  { id: "checkout", name: "Checkout.com", ats: "greenhouse", boardToken: "checkout", category: "finance", region: "Global" },
  { id: "chainalysis", name: "Chainalysis", ats: "greenhouse", boardToken: "chainalysis", category: "finance", region: "Global" },
  { id: "santander", name: "Santander", ats: "greenhouse", boardToken: "santander", category: "finance", region: "Global" },
  { id: "hsbc", name: "HSBC", ats: "greenhouse", boardToken: "hsbc", category: "finance", region: "Global" },
  { id: "jpmorgan", name: "JPMorgan Chase", ats: "greenhouse", boardToken: "jpmorgan", category: "finance", region: "Global" },
  { id: "blackrock", name: "BlackRock", ats: "greenhouse", boardToken: "blackrock", category: "finance", region: "Global" },
  { id: "goldmansachs", name: "Goldman Sachs", ats: "greenhouse", boardToken: "goldmansachs", category: "finance", region: "Global" },
  { id: "vanguard", name: "Vanguard", ats: "greenhouse", boardToken: "vanguard", category: "finance", region: "Global" },
  { id: "fidelity", name: "Fidelity", ats: "greenhouse", boardToken: "fidelity", category: "finance", region: "US" },

  // ===== LEVER COMPANIES =====
  { id: "medium", name: "Medium", ats: "lever", boardToken: "medium", category: "writing", region: "Global" },
  { id: "substack", name: "Substack", ats: "lever", boardToken: "substack", category: "writing", region: "Global" },
  { id: "ghost", name: "Ghost", ats: "lever", boardToken: "ghost", category: "writing", region: "Global" },
  { id: "theinformation", name: "The Information", ats: "lever", boardToken: "theinformation", category: "writing", region: "US" },
  { id: "axios", name: "Axios", ats: "lever", boardToken: "axios", category: "writing", region: "US" },
  { id: "voxmedia", name: "Vox Media", ats: "lever", boardToken: "voxmedia", category: "writing", region: "US" },
  { id: "buzzfeed", name: "BuzzFeed", ats: "lever", boardToken: "buzzfeed", category: "writing", region: "US" },
  { id: "vice", name: "Vice Media", ats: "lever", boardToken: "vice", category: "writing", region: "Global" },
  { id: "newyorktimes", name: "New York Times", ats: "lever", boardToken: "newyorktimes", category: "writing", region: "US" },
  { id: "washingtonpost", name: "Washington Post", ats: "lever", boardToken: "washingtonpost", category: "writing", region: "US" },
  { id: "economist", name: "The Economist", ats: "lever", boardToken: "economist", category: "writing", region: "Global" },
  { id: "bloombergmedia", name: "Bloomberg Media", ats: "lever", boardToken: "bloombergmedia", category: "writing", region: "Global" },
  { id: "reuters", name: "Reuters", ats: "lever", boardToken: "reuters", category: "writing", region: "Global" },
  { id: "associatedpress", name: "Associated Press", ats: "lever", boardToken: "associatedpress", category: "writing", region: "Global" },
  { id: "propublica", name: "ProPublica", ats: "lever", boardToken: "propublica", category: "writing", region: "US" },
  { id: "texastribune", name: "Texas Tribune", ats: "lever", boardToken: "texastribune", category: "writing", region: "US" },
  { id: "opensecrets", name: "OpenSecrets", ats: "lever", boardToken: "opensecrets", category: "research", region: "US" },
  { id: "chalkbeat", name: "Chalkbeat", ats: "lever", boardToken: "chalkbeat", category: "writing", region: "US" },
  { id: "khanacademy", name: "Khan Academy", ats: "lever", boardToken: "khanacademy", category: "nonprofit", region: "Global" },
  { id: "duolingo", name: "Duolingo", ats: "lever", boardToken: "duolingo", category: "tech", region: "Global" },
  { id: "coursera", name: "Coursera", ats: "lever", boardToken: "coursera", category: "tech", region: "Global" },
  { id: "udemy", name: "Udemy", ats: "lever", boardToken: "udemy", category: "tech", region: "Global" },

  // ===== ASHBY COMPANIES =====
  { id: "anduril", name: "Anduril", ats: "ashby", boardToken: "anduril", category: "tech", region: "US" },
  { id: "anthropic", name: "Anthropic", ats: "ashby", boardToken: "anthropic", category: "tech", region: "US" },
  { id: "openai", name: "OpenAI", ats: "ashby", boardToken: "openai", category: "tech", region: "US" },
  { id: "scaleai", name: "Scale AI", ats: "ashby", boardToken: "scaleai", category: "tech", region: "US" },
  { id: "perplexity", name: "Perplexity", ats: "ashby", boardToken: "perplexity", category: "tech", region: "US" },
  { id: "midjourney", name: "Midjourney", ats: "ashby", boardToken: "midjourney", category: "tech", region: "US" },
  { id: "runwayml", name: "Runway", ats: "ashby", boardToken: "runwayml", category: "tech", region: "US" },
  { id: "deel", name: "Deel", ats: "ashby", boardToken: "deel", category: "business", region: "Global" },
  { id: "remotecom", name: "Remote", ats: "ashby", boardToken: "remote", category: "business", region: "Global" },
  { id: "vercel", name: "Vercel", ats: "ashby", boardToken: "vercel", category: "tech", region: "Global" },
  { id: "supabase", name: "Supabase", ats: "ashby", boardToken: "supabase", category: "tech", region: "Global" },
  { id: "raycast", name: "Raycast", ats: "ashby", boardToken: "raycast", category: "tech", region: "Global" },
  { id: "cursor", name: "Cursor", ats: "ashby", boardToken: "cursor", category: "tech", region: "Global" },
  { id: "lovable", name: "Lovable", ats: "ashby", boardToken: "lovable", category: "tech", region: "EU" },
  { id: "elevenlabs", name: "ElevenLabs", ats: "ashby", boardToken: "elevenlabs", category: "tech", region: "Global" },
  { id: "windsurf", name: "Windsurf (Codeium)", ats: "ashby", boardToken: "codeium", category: "tech", region: "US" },
  { id: "mistral", name: "Mistral AI", ats: "ashby", boardToken: "mistral", category: "tech", region: "EU" },
  { id: "poolside", name: "Poolside", ats: "ashby", boardToken: "poolside", category: "tech", region: "EU" },
  { id: "hcompany", name: "H Company", ats: "ashby", boardToken: "hcompany", category: "tech", region: "EU" },
  { id: "photoroom", name: "Photoroom", ats: "ashby", boardToken: "photoroom", category: "tech", region: "EU" },
  { id: "alan", name: "Alan", ats: "ashby", boardToken: "alan", category: "tech", region: "EU" },
  { id: "qonto", name: "Qonto", ats: "ashby", boardToken: "qonto", category: "finance", region: "EU" },
  { id: "pennylane", name: "Pennylane", ats: "ashby", boardToken: "pennylane", category: "finance", region: "EU" },
  { id: "swile", name: "Swile", ats: "ashby", boardToken: "swile", category: "finance", region: "EU" },
  { id: "spendesk", name: "Spendesk", ats: "ashby", boardToken: "spendesk", category: "finance", region: "EU" },
  { id: "agoric", name: "Agoric", ats: "ashby", boardToken: "agoric", category: "finance", region: "US" },

  // ===== WORKABLE COMPANIES =====
  { id: "automattic", name: "Automattic", ats: "workable", boardToken: "automattic", category: "tech", region: "Global" },
  { id: "hotjar", name: "Hotjar", ats: "workable", boardToken: "hotjar", category: "tech", region: "EU" },
  { id: "toggl", name: "Toggl", ats: "workable", boardToken: "toggl", category: "tech", region: "EU" },
  { id: "buffer", name: "Buffer", ats: "workable", boardToken: "buffer", category: "tech", region: "Global" },
  { id: "doist", name: "Doist", ats: "workable", boardToken: "doist", category: "tech", region: "Global" },
  { id: "invision", name: "InVision", ats: "workable", boardToken: "invision", category: "tech", region: "US" },
  { id: "typeform", name: "Typeform", ats: "workable", boardToken: "typeform", category: "tech", region: "EU" },
  { id: "transferwise", name: "Wise (TransferWise)", ats: "workable", boardToken: "transferwise", category: "finance", region: "Global" },
  { id: "tractable", name: "Tractable", ats: "workable", boardToken: "tractable", category: "tech", region: "UK" },
  { id: "improbable", name: "Improbable", ats: "workable", boardToken: "improbable", category: "tech", region: "UK" },
  { id: "graphcore", name: "Graphcore", ats: "workable", boardToken: "graphcore", category: "tech", region: "UK" },
  { id: "stabilityai", name: "Stability AI", ats: "workable", boardToken: "stabilityai", category: "tech", region: "UK" },
  { id: "synthesia", name: "Synthesia", ats: "workable", boardToken: "synthesia", category: "tech", region: "UK" },
  { id: "heights", name: "Heights", ats: "workable", boardToken: "heights", category: "tech", region: "UK" },
  { id: "hereweare", name: "Here We Are", ats: "workable", boardToken: "hereweare", category: "tech", region: "Global" },

  // ===== BREEZY COMPANIES =====
  { id: "remoteyear", name: "Remote Year", ats: "breezy", boardToken: "remoteyear", category: "business", region: "Global" },
  { id: "wifitribe", name: "WiFi Tribe", ats: "breezy", boardToken: "wifitribe", category: "business", region: "Global" },
  { id: "outsite", name: "Outsite", ats: "breezy", boardToken: "outsite", category: "business", region: "Global" },
  { id: "selina", name: "Selina", ats: "breezy", boardToken: "selina", category: "business", region: "Global" },
  { id: "nomadlist", name: "Nomad List", ats: "breezy", boardToken: "nomadlist", category: "data", region: "Global" },
  { id: "flexjobs", name: "FlexJobs", ats: "breezy", boardToken: "flexjobs", category: "business", region: "US" },
  { id: "weworkremotely", name: "We Work Remotely", ats: "breezy", boardToken: "weworkremotely", category: "business", region: "Global" },
  { id: "remotive", name: "Remotive", ats: "breezy", boardToken: "remotive", category: "business", region: "Global" },
  { id: "nodesk", name: "NoDesk", ats: "breezy", boardToken: "nodesk", category: "business", region: "Global" },
  { id: "remoteok", name: "Remote OK", ats: "breezy", boardToken: "remoteok", category: "business", region: "Global" },

  // ===== RECRUITEE COMPANIES =====
  { id: "bolt", name: "Bolt", ats: "recruitee", boardToken: "bolt", category: "tech", region: "EU" },
  { id: "wise", name: "Wise", ats: "recruitee", boardToken: "wise", category: "finance", region: "Global" },
  { id: "messagebird", name: "MessageBird", ats: "recruitee", boardToken: "messagebird", category: "tech", region: "EU" },
  { id: "mollie", name: "Mollie", ats: "recruitee", boardToken: "mollie", category: "finance", region: "EU" },
  { id: "bunq", name: "Bunq", ats: "recruitee", boardToken: "bunq", category: "finance", region: "EU" },
  { id: "picnic", name: "Picnic", ats: "recruitee", boardToken: "picnic", category: "tech", region: "EU" },
  { id: "adidas", name: "Adidas", ats: "recruitee", boardToken: "adidas", category: "business", region: "EU" },
  { id: "zalando", name: "Zalando", ats: "recruitee", boardToken: "zalando", category: "business", region: "EU" },
  { id: "hellofresh", name: "HelloFresh", ats: "recruitee", boardToken: "hellofresh", category: "business", region: "Global" },
  { id: "deliveryhero", name: "Delivery Hero", ats: "recruitee", boardToken: "deliveryhero", category: "business", region: "Global" },

  // ===== SMARTRECRUITERS COMPANIES =====
  { id: "bmw", name: "BMW", ats: "smartrecruiters", boardToken: "bmw", category: "business", region: "EU" },
  { id: "siemens", name: "Siemens", ats: "smartrecruiters", boardToken: "siemens", category: "business", region: "EU" },
  { id: "bosch", name: "Bosch", ats: "smartrecruiters", boardToken: "bosch", category: "business", region: "EU" },
  { id: "pwc", name: "PwC", ats: "smartrecruiters", boardToken: "pwc", category: "business", region: "Global" },
  { id: "kpmg", name: "KPMG", ats: "smartrecruiters", boardToken: "kpmg", category: "business", region: "Global" },
  { id: "ey", name: "EY", ats: "smartrecruiters", boardToken: "ey", category: "business", region: "Global" },
  { id: "volkswagen", name: "Volkswagen", ats: "smartrecruiters", boardToken: "volkswagen", category: "business", region: "EU" },
  { id: "airbus", name: "Airbus", ats: "smartrecruiters", boardToken: "airbus", category: "business", region: "EU" },
  { id: "sanofi", name: "Sanofi", ats: "smartrecruiters", boardToken: "sanofi", category: "business", region: "EU" },
  { id: "novartis", name: "Novartis", ats: "smartrecruiters", boardToken: "novartis", category: "business", region: "Global" },
  { id: "ikea", name: "IKEA", ats: "smartrecruiters", boardToken: "ikea", category: "business", region: "Global" },
  { id: "nestle", name: "Nestle", ats: "smartrecruiters", boardToken: "nestle", category: "business", region: "Global" },
  { id: "unilever", name: "Unilever", ats: "smartrecruiters", boardToken: "unilever", category: "business", region: "Global" },

  // ===== PERSONIO COMPANIES =====
  { id: "personio", name: "Personio (own jobs)", ats: "personio", boardToken: "personio", category: "tech", region: "EU" },
  { id: "celonis", name: "Celonis", ats: "personio", boardToken: "celonis", category: "tech", region: "EU" },
  { id: "tradebe", name: "Tradebe", ats: "personio", boardToken: "tradebe", category: "climate", region: "EU" },
  { id: "nordigen", name: "Nordigen", ats: "personio", boardToken: "nordigen", category: "finance", region: "EU" },
  { id: "gorillas", name: "Gorillas", ats: "personio", boardToken: "gorillas", category: "tech", region: "EU" },
  { id: "flink", name: "Flink", ats: "personio", boardToken: "flink", category: "tech", region: "EU" },
  { id: "tier", name: "Tier Mobility", ats: "personio", boardToken: "tier", category: "tech", region: "EU" },
  { id: "enpal", name: "Enpal", ats: "personio", boardToken: "enpal", category: "climate", region: "EU" },
  { id: "zolar", name: "Zolar", ats: "personio", boardToken: "zolar", category: "climate", region: "EU" },
  { id: "1komma5", name: "1Komma5", ats: "personio", boardToken: "1komma5", category: "climate", region: "EU" },

  // ===== MORE GREENHOUSE: MEDIA / CONTENT / WRITING =====
  { id: "conde-nast", name: "Conde Nast", ats: "greenhouse", boardToken: "condenast", category: "writing", region: "Global" },
  { id: "hearst", name: "Hearst", ats: "greenhouse", boardToken: "hearst", category: "writing", region: "US" },
  { id: "dotdash", name: "Dotdash Meredith", ats: "greenhouse", boardToken: "dotdash", category: "writing", region: "US" },
  { id: "morningbrew", name: "Morning Brew", ats: "greenhouse", boardToken: "morningbrew", category: "writing", region: "US" },
  { id: "insiderinc", name: "Insider Inc", ats: "greenhouse", boardToken: "insiderinc", category: "writing", region: "US" },
  { id: "theatlantic", name: "The Atlantic", ats: "greenhouse", boardToken: "theatlantic", category: "writing", region: "US" },
  { id: "newyorker", name: "The New Yorker", ats: "greenhouse", boardToken: "newyorker", category: "writing", region: "US" },
  { id: "guardian", name: "The Guardian", ats: "greenhouse", boardToken: "guardian", category: "writing", region: "UK" },
  { id: "ft", name: "Financial Times", ats: "greenhouse", boardToken: "ft", category: "writing", region: "UK" },
  { id: "bbc", name: "BBC", ats: "greenhouse", boardToken: "bbc", category: "writing", region: "UK" },

  // ===== MORE GREENHOUSE: TECH / STARTUPS =====
  { id: "flexport", name: "Flexport", ats: "greenhouse", boardToken: "flexport", category: "business", region: "US" },
  { id: "rippling", name: "Rippling", ats: "greenhouse", boardToken: "rippling", category: "tech", region: "US" },
  { id: "gusto", name: "Gusto", ats: "greenhouse", boardToken: "gusto", category: "tech", region: "US" },
  { id: "webflow", name: "Webflow", ats: "greenhouse", boardToken: "webflow", category: "tech", region: "US" },
  { id: "airtable", name: "Airtable", ats: "greenhouse", boardToken: "airtable", category: "tech", region: "US" },
  { id: "clickup", name: "ClickUp", ats: "greenhouse", boardToken: "clickup", category: "tech", region: "Global" },
  { id: "monday", name: "Monday.com", ats: "greenhouse", boardToken: "monday", category: "tech", region: "Global" },
  { id: "wix", name: "Wix", ats: "greenhouse", boardToken: "wix", category: "tech", region: "Global" },
  { id: "fiverr", name: "Fiverr", ats: "greenhouse", boardToken: "fiverr", category: "business", region: "Global" },
  { id: "upwork", name: "Upwork", ats: "greenhouse", boardToken: "upwork", category: "business", region: "Global" },
  { id: "toptal", name: "Toptal", ats: "greenhouse", boardToken: "toptal", category: "business", region: "Global" },
  { id: "andela", name: "Andela", ats: "greenhouse", boardToken: "andela", category: "tech", region: "Global" },
  { id: "turing", name: "Turing", ats: "greenhouse", boardToken: "turing", category: "tech", region: "Global" },
  { id: "contra", name: "Contra", ats: "greenhouse", boardToken: "contra", category: "business", region: "Global" },

  // ===== MORE LEVER: STARTUPS =====
  { id: "a16z", name: "Andreessen Horowitz", ats: "lever", boardToken: "a16z", category: "finance", region: "US" },
  { id: "sequoiacap", name: "Sequoia Capital", ats: "lever", boardToken: "sequoiacap", category: "finance", region: "US" },
  { id: "ycombinator", name: "Y Combinator", ats: "lever", boardToken: "ycombinator", category: "finance", region: "US" },
  { id: "techstars", name: "Techstars", ats: "lever", boardToken: "techstars", category: "finance", region: "Global" },
  { id: "500startups", name: "500 Global", ats: "lever", boardToken: "500startups", category: "finance", region: "Global" },
  { id: "multiverse", name: "Multiverse", ats: "lever", boardToken: "multiverse", category: "tech", region: "UK" },
  { id: "checkoutcom", name: "Checkout.com", ats: "lever", boardToken: "checkoutcom", category: "finance", region: "Global" },
  { id: "rapidapi", name: "RapidAPI", ats: "lever", boardToken: "rapidapi", category: "tech", region: "Global" },
  { id: "gocardless", name: "GoCardless", ats: "lever", boardToken: "gocardless", category: "finance", region: "UK" },
  { id: "truelayer", name: "TrueLayer", ats: "lever", boardToken: "truelayer", category: "finance", region: "UK" },
  { id: "cleo", name: "Cleo AI", ats: "lever", boardToken: "cleo", category: "finance", region: "UK" },
  { id: "zopa", name: "Zopa", ats: "lever", boardToken: "zopa", category: "finance", region: "UK" },
  { id: "atom bank", name: "Atom Bank", ats: "lever", boardToken: "atombank", category: "finance", region: "UK" },
  { id: "starling", name: "Starling Bank", ats: "lever", boardToken: "starling", category: "finance", region: "UK" },

  // ===== MORE LEVER: MEDIA / CONTENT =====
  { id: "ted", name: "TED", ats: "lever", boardToken: "ted", category: "writing", region: "Global" },
  { id: "masterclass", name: "MasterClass", ats: "lever", boardToken: "masterclass", category: "writing", region: "US" },
  { id: "skillshare", name: "Skillshare", ats: "lever", boardToken: "skillshare", category: "tech", region: "US" },
  { id: "patreon", name: "Patreon", ats: "lever", boardToken: "patreon", category: "tech", region: "US" },
  { id: "kickstarter", name: "Kickstarter", ats: "lever", boardToken: "kickstarter", category: "tech", region: "US" },
  { id: "etsy", name: "Etsy", ats: "lever", boardToken: "etsy", category: "tech", region: "Global" },
  { id: "eventbrite", name: "Eventbrite", ats: "lever", boardToken: "eventbrite", category: "tech", region: "Global" },
  { id: "calendly", name: "Calendly", ats: "lever", boardToken: "calendly", category: "tech", region: "US" },

  // ===== ADDITIONAL GREENHOUSE: NONPROFITS / FOUNDATIONS =====
  { id: "gatesfoundation", name: "Bill & Melinda Gates Foundation", ats: "greenhouse", boardToken: "gatesfoundation", category: "nonprofit", region: "Global" },
  { id: "fordfoundation", name: "Ford Foundation", ats: "greenhouse", boardToken: "fordfoundation", category: "nonprofit", region: "Global" },
  { id: "rockefellerfoundation", name: "Rockefeller Foundation", ats: "greenhouse", boardToken: "rockefellerfoundation", category: "nonprofit", region: "Global" },
  { id: "macfound", name: "MacArthur Foundation", ats: "greenhouse", boardToken: "macfound", category: "nonprofit", region: "US" },
  { id: "openphilanthropy", name: "Open Philanthropy", ats: "greenhouse", boardToken: "openphilanthropy", category: "nonprofit", region: "US" },
  { id: "effectivealtruism", name: "Effective Altruism", ats: "greenhouse", boardToken: "effectivealtruism", category: "nonprofit", region: "Global" },
  { id: "givedirectly", name: "GiveDirectly", ats: "greenhouse", boardToken: "givedirectly", category: "nonprofit", region: "Global" },
  { id: "80000hours", name: "80,000 Hours", ats: "greenhouse", boardToken: "80000hours", category: "nonprofit", region: "Global" },
  { id: "ourworldindata", name: "Our World in Data", ats: "greenhouse", boardToken: "ourworldindata", category: "research", region: "Global" },
  { id: "climatepolicyinitiative", name: "Climate Policy Initiative", ats: "greenhouse", boardToken: "climatepolicyinitiative", category: "climate", region: "Global" },
  { id: "ceres", name: "Ceres", ats: "greenhouse", boardToken: "ceres", category: "climate", region: "US" },
  { id: "rmi", name: "RMI", ats: "greenhouse", boardToken: "rmi", category: "climate", region: "Global" },
  { id: "energyinnovation", name: "Energy Innovation", ats: "greenhouse", boardToken: "energyinnovation", category: "climate", region: "US" },
  { id: "breakthrough", name: "Breakthrough Institute", ats: "greenhouse", boardToken: "breakthrough", category: "climate", region: "US" },
  { id: "carbonbrief", name: "Carbon Brief", ats: "greenhouse", boardToken: "carbonbrief", category: "climate", region: "UK" },
  { id: "iea", name: "International Energy Agency", ats: "greenhouse", boardToken: "iea", category: "climate", region: "Global" },
  { id: "irena", name: "IRENA", ats: "greenhouse", boardToken: "irena", category: "climate", region: "Global" },
  { id: "wri", name: "World Resources Institute", ats: "greenhouse", boardToken: "wri", category: "climate", region: "Global" },
  { id: "edf", name: "Environmental Defense Fund", ats: "greenhouse", boardToken: "edf", category: "climate", region: "US" },
  { id: "nrdc", name: "NRDC", ats: "greenhouse", boardToken: "nrdc", category: "climate", region: "US" },
  { id: "sierraclub", name: "Sierra Club", ats: "greenhouse", boardToken: "sierraclub", category: "climate", region: "US" },
  { id: "greenpeace", name: "Greenpeace", ats: "greenhouse", boardToken: "greenpeace", category: "climate", region: "Global" },
  { id: "wwf", name: "World Wildlife Fund", ats: "greenhouse", boardToken: "wwf", category: "climate", region: "Global" },
  { id: "tnc", name: "The Nature Conservancy", ats: "greenhouse", boardToken: "tnc", category: "climate", region: "Global" },
  { id: "conservation", name: "Conservation International", ats: "greenhouse", boardToken: "conservation", category: "climate", region: "Global" },

  // ===== MORE ASHBY: AI / DATA / CLIMATE =====
  { id: "cohere", name: "Cohere", ats: "ashby", boardToken: "cohere", category: "tech", region: "Global" },
  { id: "characterai", name: "Character.AI", ats: "ashby", boardToken: "characterai", category: "tech", region: "US" },
  { id: "replit", name: "Replit", ats: "ashby", boardToken: "replit", category: "tech", region: "US" },
  { id: "sourcegraph", name: "Sourcegraph", ats: "ashby", boardToken: "sourcegraph", category: "tech", region: "Global" },
  { id: "hex", name: "Hex", ats: "ashby", boardToken: "hex", category: "tech", region: "US" },
  { id: "observable", name: "Observable", ats: "ashby", boardToken: "observable", category: "data", region: "US" },
  { id: "dbtlabs", name: "dbt Labs", ats: "ashby", boardToken: "dbtlabs", category: "data", region: "US" },
  { id: "fishtown", name: "Fishtown Analytics", ats: "ashby", boardToken: "fishtown", category: "data", region: "US" },
  { id: "hightouch", name: "Hightouch", ats: "ashby", boardToken: "hightouch", category: "data", region: "US" },
  { id: "census", name: "Census", ats: "ashby", boardToken: "census", category: "data", region: "US" },
  { id: "rudderstack", name: "RudderStack", ats: "ashby", boardToken: "rudderstack", category: "data", region: "US" },
  { id: "watershed", name: "Watershed", ats: "ashby", boardToken: "watershed", category: "climate", region: "Global" },
  { id: "patch", name: "Patch", ats: "ashby", boardToken: "patch", category: "climate", region: "US" },
  { id: "sylvera", name: "Sylvera", ats: "ashby", boardToken: "sylvera", category: "climate", region: "UK" },
  { id: "pachama", name: "Pachama", ats: "ashby", boardToken: "pachama", category: "climate", region: "US" },
  { id: "ncx", name: "NCX", ats: "ashby", boardToken: "ncx", category: "climate", region: "US" },
];
